### ISSUE TITLE
Macro win-yt link broke

### ISSUE THREAD

**Issue by Gamengday** [prcutler/awesome-macropad#6]
The link to DjDevon3 youtube macro script broke, found the new one for you.
https://github.com/DJDevon3/My_Circuit_Python_Projects/blob/main/Boards/raspberrypi/Adafruit%20Macropad%20RP2040/Jons%20Macropad/macros/win-youtube.py

**Comment by prcutler** [comment]
Thanks for letting me know, I really appreciate it!
